<?php
/**
 * ShipperHQ
 *
 * @category ShipperHQ
 * @package ShipperHQ\Tracker
 * @copyright Copyright (c) 2016 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

use ShipperHQ\Tracker\Helper\Track;
// @codingStandardsIgnoreFile
$_shipment = $block->getShipment();
$_order = $block->getOrder();
$rplChars = array(' ' => '');
$string = '';
if ($this->getOrder()) {
    $string = $this->getOrder()->getShippingAddress()->getPostcode();
}
$zipCode = strtr($string, $rplChars);
?>
<?php if ($_shipment && $_order && $_shipment->getTracks()): ?>
    <br/>
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */ __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_shipment->getTracks() as $_item): ?> <!--SHQ18-1992 Changed from getAllTracks-->
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                <?php $_url = $this->helper(Track::class)->getTrackUrl($_item->getTitle(),
                    $_item->getNumber(), $zipCode) ?>

                <?php if ($_url !== ''): ?>
                    <td><a href="<?= $block->escapeUrl($_url) ?>"><?= $block->escapeHtml($_item->getNumber()) ?></a></td>
                <?php else: ?>
                    <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
                <?php endif; ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
